language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
env:
  global:
  - secure: d3IUjn1Up7iIczFEJefWLmmbtIecWr3Yf1ZDuTly65XOcT7yMbg4E2dz4UcWlbNx/A9xUDB0QS0aE1JawXVnme2rjpIe8xt4SdmveXttEetM20/Fc9IVHbK/19CZf3dGWKed4Sa+ZM0VIEH0rl4x0tWUzQx0M3nlkU057VtbIQT77qfTRjCiP+04C0QiqNJ+PxbG894jaNnIStVAgdOlH/1V0aCP59u7fuMtCdTrfOeZdT0am4raok+jTTar5UFc+Ts27TkhCkdVQK1lcEABDi9RQbXoWJpp0tXC6OC7otd4S3dwYa4rBIlY6FJ5hq78on1ub6G4gL5mHS6Ip2HY7fCEehmJQ9sZ8q6pbJXyogGuDcUJLTw/5qDCKdyD+vjXDYshrnpGySuE72MrvCf/JmCzY990J1sHLZ3BdEX567BEMvoVXaSOXp2qgeJoMQ2ZkqSqwhOvZlICpE65oW9KFzueN+pikgMEHb/5wZ4ZhAON7e1Cf9tAqB6ADgiudyQIZSKhz1y8BPbV6TGMA1Xfxlvp/bZPSlulhs+Q/kccKxpHfJ4So2Gjr+3tLf9qhEkC9+IdppE9vEEseTjgO2koD4+iX9GYsga49FYz6//6y+Ha4Fzcf1aDC1oqgKmbIdEu9JcOQ1qxHzJvospLJ2Fqcm5uwtNxVr9woLkYY428oTo=
  - secure: FvcbBIkEwGuYXOx8st6mtA/QZPmPeRohGuZRRA9YWxj/lK8cV/eT1slscVtDBAT8IyeKLS7MBHbkzQvmYM+DeSKtBkZCkdJlPVD7I0HCuPqJ45Cpgo8xsrvrVrrda0cYEeGVtfAJbF7y2ea2ioL/c5FAqho+pmLteyulAEwSftT+jwgQ6SbzNKVTeEG7uZuQckdHz1scC8NzA+KzFiDXE93PPc1XFuXCLO8b2bFQ1PzYOmQ1SdFmWxX99QYjrgmzoC/d4IFKHOABeBB6NSk1Mtz0Vw4SEDKh6iK8Qyzvfo+lG0gQFwIvwNgIWoAbBSkYJrRm4qEwRiQ/EmpTgOS+uc+6rHuFMOJx+BzgstdlcPdt3deGZZAbctv4nHFNyBxjqRJfNeP8Veskf7pjTsBgjUhRZSUtPZSFE5SO06P1xayB0VGKE+mG4iebt3IUDOiqMeVO/S4kc8qHUNADECStyMzDRnIk4pnSsXiRjCkRo1Q7S1InewdDtyq0NoKJo4rH4Dqo/+y/8Z7Ru4EXFdO5DH3iR57OIhYIodab10fFigt97VpqSa971cAsUKbQlyvGsVnL+xCLS6S8V/TiSQhlJdDtUd8Wtld8PAaTN9q9Uvk//VbXh4iP8Tmq88oGa48o27jERsIDy7DwjouOI9FWLbviFL3X86af0DHfSQ6NyR8=
