language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"  == "dhis2/interpretation-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ];then
      mvn clean deploy --settings deploy/settings.xml && exit 0;
  fi 
env:
  global:
  - secure: d3IUjn1Up7iIczFEJefWLmmbtIecWr3Yf1ZDuTly65XOcT7yMbg4E2dz4UcWlbNx/A9xUDB0QS0aE1JawXVnme2rjpIe8xt4SdmveXttEetM20/Fc9IVHbK/19CZf3dGWKed4Sa+ZM0VIEH0rl4x0tWUzQx0M3nlkU057VtbIQT77qfTRjCiP+04C0QiqNJ+PxbG894jaNnIStVAgdOlH/
1V0aCP59u7fuMtCdTrfOeZdT0am4raok+jTTar5UFc+Ts27TkhCkdVQK1lcEABDi9RQbXoWJpp0tXC6OC7otd4S3dwYa4rBIlY6FJ5hq78on1ub6G4gL5mHS6Ip2HY7fCEehmJQ9sZ8q6pbJXyogGuDcUJLTw/5qDCKdyD+vjXDYshrnpGySuE72MrvCf/JmCzY990J1sHLZ3BdEX567BEMvoVXaSOXp2q
geJoMQ2ZkqSqwhOvZlICpE65oW9KFzueN+pikgMEHb/5wZ4ZhAON7e1Cf9tAqB6ADgiudyQIZSKhz1y8BPbV6TGMA1Xfxlvp/bZPSlulhs+Q/kccKxpHfJ4So2Gjr+3tLf9qhEkC9+IdppE9vEEseTjgO2koD4+iX9GYsga49FYz6//6y+Ha4Fzcf1aDC1oqgKmbIdEu9JcOQ1qxHzJvospLJ2Fqcm5uwt
NxVr9woLkYY428oTo=
  - secure: FvcbBIkEwGuYXOx8st6mtA/QZPmPeRohGuZRRA9YWxj/lK8cV/eT1slscVtDBAT8IyeKLS7MBHbkzQvmYM+DeSKtBkZCkdJlPVD7I0HCuPqJ45Cpgo8xsrvrVrrda0cYEeGVtfAJbF7y2ea2ioL/c5FAqho+pmLteyulAEwSftT+jwgQ6SbzNKVTeEG7uZuQckdHz1scC8NzA+KzFiDXE9
3PPc1XFuXCLO8b2bFQ1PzYOmQ1SdFmWxX99QYjrgmzoC/d4IFKHOABeBB6NSk1Mtz0Vw4SEDKh6iK8Qyzvfo+lG0gQFwIvwNgIWoAbBSkYJrRm4qEwRiQ/EmpTgOS+uc+6rHuFMOJx+BzgstdlcPdt3deGZZAbctv4nHFNyBxjqRJfNeP8Veskf7pjTsBgjUhRZSUtPZSFE5SO06P1xayB0VGKE+mG4ieb
t3IUDOiqMeVO/S4kc8qHUNADECStyMzDRnIk4pnSsXiRjCkRo1Q7S1InewdDtyq0NoKJo4rH4Dqo/+y/8Z7Ru4EXFdO5DH3iR57OIhYIodab10fFigt97VpqSa971cAsUKbQlyvGsVnL+xCLS6S8V/TiSQhlJdDtUd8Wtld8PAaTN9q9Uvk//VbXh4iP8Tmq88oGa48o27jERsIDy7DwjouOI9FWLbviFL
3X86af0DHfSQ6NyR8=
notifications:
  slack:
    secure: nybqT1rPwRfokyqStmhSl5/CFxXENrDYC04zxn6lSgiI42IAYTSBX+CCFqjPkcFBk7ufbJsxgmnmPX7aSNKahvCEj/WwM3JmtVZ6cb/xN0qMkZJtDDuU7jhF+6ziOds5Of3WbG9Xzs17IYHm4bEVAfdF383dc10EJkhdM4+2cgRgWj8xf02DlN8694sBXXN4w4EjeI7N7M/6ZcDJ16FS+O
QgV6nbJsb0S9q7+XOyPST4x+2u/Uti+3SlBtqR9kJDfUKj0tcQ0CLmdtyS4doBdnfHfLxr9uNhue6xTZ9cuUk0POT30UciBj2Ol/0K8Y35eSPhq2bp6IgSi/Q8TtULhUkBS1ntSfINXN7+U6K6kdtZZ97tGSuM7/G4F0SU9j+Ekxw8ROzliiX4yQCphjIzftsJlwUtj4wtxYLgFFvne8pMRIYJXll1dQCW
2Dp7r/W/KjmQ3Heq4jNYXobUHJE914WUwqPr+ODrcTkmGa9334WwcPeM0EZdLrWb2eR83TXLyzm9ZlcS6I4FuyYb9v6S0dlPFTwyUu6UUJLpSwdbWAJE9wmqdJHbvcj724RU1qEb4N/38SONKzvhmE0iaO2GPpB0ZVRnvOEMEW1m3b1JFNAeON6md6u39aaf98KDjOE/5stQ7P1RwD/b7S0OTP8f0D7MqX
KA7H+Da0WdmjfS2Xc=
    on_success: change
    on_failure: always

