language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"  ==
  "dhis2/interpretation-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ];then mvn
  clean deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: Am59kq0G4hIpTrp2sLYoydO2MwvRuu354KzrnLeQDxhY5ISrUCAGJeM3gWwmMSvjyf/aqhgS60Mosr+7v0UoD5bm7UD3sI/S613ORr9Gk6ecNWVK1VVjOF7ptvL/DbhAjJpYV7/89XqyyMGjqChu5nEGPmMGafVxQF65Dpb3RDTSEruMPn4NRDIe5a5mqez28xDinfT5ESRj4FY2TY0tCZMUVRYz1UQ8Rm8ggyIi8pQw1g+uQHu4hw8K+EJuXYUNZ5YCjb+LzUD/mt+XPeENYhv9gZE3W3fpMYtasF/D+gkX6DwxhnTP0dcrCZhszRvCO1LhfyQLlS39BY6XlUb6ylpKbhkwSGYTloXH6n5fFbGa/XUIKZOugi+y00IQMqw5G6jfHUIiFBybpej6I/jO2mlX7s6qGMsQdw/30Pq4/AD/OJ+Lgx0NcqC1p81fw7dVt2M8IwTrh8Wy5Q8ssyhI5z5jqKdgb5qIFM+CEkA9iWDdl75AyNyYCsJ5yl6Lz5A+y7IENHUtvMduFCzTL71M/4tKbmrINCJkmCvCzcoZF4gxDx0iINwdA0iBjO9zPSVTEsw8dU1BnARfUbvICMZEJMnPJkk8rePWINA7zpX3MYKTbzM0tyIYR+KS16aQXxze/hol76gnL7+9ch7ZWvJb/e1vkynvVMxWGssk/R7Ux4U=
  - secure: DdK4Prf4yiZma2DDcjMhPnnQP+svj/r8DXzPSVwMeBGqoqwEx0xXeuJc37UtTTlOrsX226DnixGeBjSNh14k3PSqhHhMNkD0iXdJSiSLMNN2mj1XsTt0q4b421nBQGriCeREUKIe9uDV2W3w6a6OYTqNavLwab6QBCRIJWJCrIrk0n+oeN8bmWJJf5WHGzHIfg9uvgNgCXmO2vzB7ojfgE/aZUZZEnLwSx3AO9Vn/b8U3ymmDAUWQqR5lfy+Z/06tOIGSPq4+63d2p8sGEWt7bdTxkM9lpokhQQcr0Md5x/kG1Xb/RNtX73HZJERvlAJevXQYlssP1t6PMY2egdQ3Up+Afqo/wyiAiZgpsvQps4whjbyV/WHsD65EY9iqOfjGxd7lLuPfMYHDBes2+QdSLXUkyrya0uxTvUcc9CnbmHwPazrXt5Ra28elFx7bxqMepOv/EMVWh23S9VnTo36uL4ivDyGXkPbnI8FaE5IA5VBjE33x3c3q55qdfRM4ILW8vRjl5fL2twe1nxAow9IxVQMDbjKtI688v5Ur5Ppe4Gsf00+dSg06ve40gjDECpdSjTx8udYiEbm7IdL6fElJIje+QzAER6AJWE3oKKIlOhckQyTknusV425b/0cAKbFw/nTvjrOCrtn8G0hNRQuamH0Jq+5Cfl7nyd9KefuA9A=
notifications:
  slack:
    secure: WdXbIGwUMzGp2O2m+EmeMy+CrCr3cOkkQU7UW9Q5dAORJl9L5FdxDA04C+NjDCwLyKnpFBR1uassTRG9opBn6rI6adAuAAPInoo7zCK4H8nCVvLsHfllOZOdZt85y5JXLDY+XIkmdg8QaX9MTf0r+oOzDnUikemWsLLgeHOtgkaqw4wq+x2CYYEr6k3lwhuZIHWe0t18xTnkRSKfFw69BoIa7GibL2+7tn3wXBtpHXN01dHkoU9vSqtJ5sYBvz/udGfvIRDU0hACKwnbXdnM6qcfU4pMKYp0pUM64AH9AjLSR0GKrENrCJYGAMNttDFOxZ5hcqF4wFop0Qg1e/gWGMoqwEBejUrlBj2p1okyjeag+NJinwoSDqqJm/1jumyfHUCf4hOfE3Lz6FKnbkegnI4DGxzN6JVUvzMwjRF7A3l9buEC3GYDjbkD0BT0+rdeQIy6rxyeD72Vwe6dw/EZXtozhGWMvdW5Qdzft3SIdGOIuJv73FiL5v40mpQYeJ9Hhg4fM/l30H/QQVWbPoiRn4oJQGD10Sj+c82bMgMfqX537OcTYTO/ntiP9GDby/jFgDf9ttxXC3yEKuGZC+deQJBz9Tu+ErDpewRUg/Kv3z/skVcyOtdUin0/8yejCH+AttwzJETBmOI0hQlr3VBeSSpvF5JL6Dz/25okajrYUN0=
    on_success: change
    on_failure: always
